### ISSUE TITLE
Add option to show/hide credentials in imlogin command

### ISSUE THREAD

**Issue by ShivamS136** [paras-lehana/utils#1]
while running `imlogin <user>@<server_alias>` shows user credentials (username and password) in the output of the command. Credentials should be secured and not visible in output. 

Though as sometimes we might require it so we can add an argument in command like `--show-cred` so that the credentials will be visible only in case of this argument is passed else only username can be shown.

**Comment by paras-lehana** [comment]
Resolved with #2.
